name: CI
on:
  push:
    branches: 
      - master

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Install GitHub CLI
        run: |
          Invoke-WebRequest -Uri "https://github.com/cli/cli/releases/latest/download/gh_2.37.0_windows_amd64.msi" -OutFile "gh-installer.msi"
          Start-Process msiexec.exe -ArgumentList "/i gh-installer.msi /quiet /norestart" -NoNewWindow -Wait
          Remove-Item -Path "gh-installer.msi"
          gh --version
          
      - name: Create binaries directory
        run: |
          mkdir backend\assets\binaries
          git clone https://github.com/cloudstack-llc/ollama.git
          Move-Item -Path "ollama\assets\ollama.exe" -Destination "backend\assets\binaries\msty-local-darwin"

          Invoke-WebRequest -Uri "https://github.com/ollama/ollama/releases/latest/download/ollama-windows-amd64.zip" -OutFile "ollama.zip" -TimeoutSec 30 -MaximumRetryCount 3

          New-Item -ItemType Directory -Path ollama-windows -Force
          powershell -command "Expand-Archive -Path ollama.zip -DestinationPath ollama-windows"
          Move-Item -Path "ollama-windows\lib" -Destination "backend\assets\binaries\lib"

          Get-ChildItem -Path "backend\assets\binaries\lib" -Force | Sort-Object LastWriteTime -Descending
        
