name: Build Test
on:
  push:
    branches:
      - 'master'
      - 'rel/**'

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - name: Pack LanceDB
      run: |
          mkdir -p backend/assets/binaries/darwin/@lancedb

          LANCEDB_X64="@lancedb/vectordb-darwin-x64"
          LANCEDB_ARM64="@lancedb/vectordb-darwin-arm64"

          VERSION_X64=$(npm show $LANCEDB_X64 version)
          VERSION_ARM64=$(npm show $LANCEDB_ARM64 version)

          npm pack $LANCEDB_X64
          npm pack $LANCEDB_ARM64

          npm pack $LANCEDB_X64
          npm pack $LANCEDB_ARM64

          mkdir vectordb-darwin-x64
          tar -xzf lancedb-vectordb-darwin-x64-$VERSION_X64.tgz -C vectordb-darwin-x64

          mkdir vectordb-darwin-arm64
          tar -xzf lancedb-vectordb-darwin-arm64-$VERSION_ARM64.tgz -C vectordb-darwin-arm64

          mv vectordb-darwin-x64 backend/assets/binaries/darwin/@lancedb
          mv vectordb-darwin-arm64 backend/assets/binaries/darwin/@lancedb

          ls -alt backend/assets/binaries/darwin/@lancedb
