name: Build
on:
  push:
    tags:
      - 'v*'
    branches:
      - 'rel/**'

jobs:
  build-macos:
    if: startsWith(github.ref, 'refs/heads/rel/mac/') || startsWith(github.ref, 'refs/tags/v')
    runs-on: macos-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set ENV for macOS
        run: |
          TAG_VERSION=${{ github.ref }}
          TAG_VERSION=${TAG_VERSION#refs/tags/}
          TAG_VERSION=${TAG_VERSION#v}
          echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV
      
      - name: Run
        run: |
          echo $TAG_VERSION
