name: CI
on:
  push:
    branches: 
      - master

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install GitHub CLI
        run: |
          choco install gh -y
          gh --version

      - name: Set RELEASE_PATH for win-auto
        run: |
          New-Item -Path ./release/1.1.1/win/auto/Msty_x64.exe -ItemType File -Force

      - name: Upload Windows-auto files
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create 1.1.1 `
          --title 1.1.1 `
          --notes "Automated release from GitHub Actions" `
          "./release/1.1.1/win/auto/Msty_x64.exe"
