name: Build
on:
  push:
    branches:
      - 'master'
      - 'rel/**'

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Extract version from package.json
        id: extract_version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "TAG_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build for rel
        if: startsWith(github.ref, 'refs/heads/rel/')
        run: |
          echo "Building macOS with version: ${{ env.TAG_VERSION }}. Beta build.."

      - name: Build for master
        if: github.ref == 'refs/heads/master'
        run: |
          echo "Building macOS with version: ${{ env.TAG_VERSION }}. Prod build.."


  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Extract version from package.json
        id: extract_version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "TAG_VERSION=$VERSION" >> $GITHUB_ENV
            
      - name: Build for rel
        if: startsWith(github.ref, 'refs/heads/rel/')
        run: |
          echo "Building Linux with version: ${{ env.TAG_VERSION }}. Beta build.."

      - name: Build for master
        if: github.ref == 'refs/heads/master'
        run: |
          echo "Building Linux with version: ${{ env.TAG_VERSION }}. Prod build.."


  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        build-config: [ win-auto, win-cpu ]


    if: "!contains(github.event.head_commit.message, '[skip-win]')"
    steps:
      - name: Check commit message
        run: |
          $commitMessage = "${{ github.event.head_commit.message }}"
          Write-Host "Commit message: $commitMessage"

          if ($commitMessage -like '*`[skip-win-auto`]*' -and "${{ matrix.build-config }}" -eq 'win-auto') {
            Write-Host "Skipping win-auto build due to '[skip-win-auto]' in commit message."
            echo "SKIP=true" >> $env:GITHUB_ENV
          } elseif ($commitMessage -like '*`[skip-win-cpu`]*' -and "${{ matrix.build-config }}" -eq 'win-cpu') {
            Write-Host "Skipping win-cpu build due to '[skip-win-cpu]' in commit message."
            echo "SKIP=true" >> $env:GITHUB_ENV
          } else {
            echo "SKIP=false" >> $env:GITHUB_ENV
          }

      - name: Check out Git repository
        if: ${{ env.SKIP != true }}
        uses: actions/checkout@v3

      - name: Extract version from package.json
        if: ${{ env.SKIP != true }}
        run: |
          $VERSION = (Get-Content package.json | ConvertFrom-Json).version
          echo "TAG_VERSION=$VERSION" >> $env:GITHUB_ENV

      - name: Build for rel
        if: ${{ env.SKIP != true }} && startsWith(github.ref, 'refs/heads/rel/')
        run: |
          echo "Building Windows with version: ${{ env.TAG_VERSION }}. Beta build.."

      - name: Build for master
        if: ${{ env.SKIP != true }} && github.ref == 'refs/heads/master'
        run: |
          echo "Building Windows with version: ${{ env.TAG_VERSION }}. Prod build.."

