name: CI
on:
  push:
    branches: 
      - master

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Install GitHub CLI
        run: |
          choco install gh -y
          gh --version

      - name: Set RELEASE_PATH for win-auto
        run: |
          "RELEASE_PATH=./release/1.1.1/win/auto" | Out-File -Append -FilePath $env:GITHUB_ENV
          New-Item -Path "${{ RELEASE_PATH }}" -ItemType Directory -Force
          New-Item -Path "${{ RELEASE_PATH }}/Msty_x64.exe" -ItemType File -Force

      - name: Upload Windows-auto files
        run: |
          gh release create 1.1.1 `
          --title 1.1.1 `
          --notes "Automated release from GitHub Actions" `
          "./release/1.1.1/win/auto/Msty_x64.exe"
