name: CI
on:
  push:
    branches: 
      - master

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install GitHub CLI
        run: |
          choco install gh -y
          gh --version

      - name: Prepare Release Files
        run: |
          $RELEASE_PATH = "./release/1.1.1/win/auto"
          New-Item -Path $RELEASE_PATH -ItemType Directory -Force
          New-Item -Path "$RELEASE_PATH/Msty_x64.exe" -ItemType File -Force

      - name: Upload Windows-auto files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the correct reference
        run: |
          gh release create 1.1.1 `
          --title 1.1.1 `
          --notes "Automated release from GitHub Actions" `
          "./release/1.1.1/win/auto/Msty_x64.exe"
